---


- name: Synchronize internet-monitoring directory.
  ansible.posix.synchronize:
    src: "internet-monitoring"
    dest: "{{ config_dir }}/"
    delete: false
    recursive: true
    perms: false
  become: false

# This is an upgrade task from 1.x to 2.x - can be removed for 3.x.
- name: Ensure internet-monitoring directory is not a Git repository.
  ansible.builtin.file:
    path: "{{ config_dir }}/internet-monitoring/.git/"
    state: absent
  become: false

- name: Copy templated internet-monitoring files into place.
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ config_dir }}/internet-monitoring/{{ item.dest }}"
    mode: 0644
  loop:
    - src: grafana-config.monitoring.j2
      dest: grafana/config.monitoring
    - src: prometheus.yml.j2
      dest: prometheus/prometheus.yml
    - src: prometheus-pinghosts.yaml.j2
      dest: prometheus/pinghosts.yaml
  notify: Restart internet-monitoring
  become: false

- name: Ensure internet-monitoring environment is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/internet-monitoring/"
    build: false
  become: false
